import React, { createContext, useContext, useState, ReactNode } from 'react';

// Define available languages
export type Language = 'en' | 'ur' | 'ko' | 'zh' | 'ar' | 'de' | 'es' | 'fr' | 'pt' | 'tr' | 'nl' | 'pl' | 'ja' | 'bn';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  // English
  en: {
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.services': 'Services',
    'nav.portfolio': 'Portfolio',
    'nav.blog': 'Blog',
    'nav.pricing': 'Pricing',
    'nav.contact': 'Contact',
    'hero.title': 'Transform Your Digital Presence',
    'hero.subtitle': 'We craft innovative digital solutions that drive growth and success for your business',
    'hero.cta': 'Get Started',
    'hero.learn': 'Learn More',
    'services.title': 'Our Services',
    'services.subtitle': 'Comprehensive digital solutions tailored to your needs',
    'services.ecommerce': 'E-commerce Development',
    'services.web': 'Website Development',
    'services.ppc': 'Google Ads (PPC)',
    'services.seo': 'Search Engine Optimization',
    'services.social': 'Social Media Marketing',
    'services.mobile': 'Mobile App Development',
    'services.software': 'Software Development',
    'services.outdoor': 'Outdoor Media Advertising',
    'services.blockchain': 'Blockchain Development',
    'about.title': 'About Us',
    'about.subtitle': 'Leading the digital transformation',
    'about.team': 'Our Team',
    'about.partners': 'Our Partners',
    'contact.title': 'Get In Touch',
    'contact.subtitle': "We'd love to hear from you",
    'contact.name': 'Name',
    'contact.email': 'Email',
    'contact.message': 'Message',
    'contact.send': 'Send Message',
    'footer.tagline': 'Innovating digital solutions for tomorrow',
    'footer.subscribe': 'Subscribe to our newsletter',
    'footer.company': 'Company',
    'footer.services': 'Services',
    'footer.resources': 'Resources',
    'common.learnMore': 'Learn More',
    'common.viewAll': 'View All',
    'common.readMore': 'Read More',
  },
  // Urdu (Pakistan)
  ur: {
    'nav.home': 'ہوم',
    'nav.about': 'ہمارے بارے میں',
    'nav.services': 'خدمات',
    'nav.portfolio': 'پورٹ فولیو',
    'nav.blog': 'بلاگ',
    'nav.pricing': 'قیمتیں',
    'nav.contact': 'رابطہ کریں',
    'hero.title': 'اپنی ڈیجیٹل موجودگی کو تبدیل کریں',
    'hero.subtitle': 'ہم جدید ڈیجیٹل حل تیار کرتے ہیں جو آپ کے کاروبار کی ترقی کو فروغ دیتے ہیں',
    'hero.cta': 'شروع کریں',
    'hero.learn': 'مزید جانیں',
    'services.title': 'ہماری خدمات',
    'services.subtitle': 'آپ کی ضروریات کے مطابق جامع ڈیجیٹل حل',
    'services.ecommerce': 'ای کامرس ڈیویلپمنٹ',
    'services.web': 'ویب سائٹ ڈیویلپمنٹ',
    'services.ppc': 'گوگل ایڈز (PPC)',
    'services.seo': 'سرچ انجن آپٹیمائزیشن',
    'services.social': 'سوشل میڈیا مارکیٹنگ',
    'services.mobile': 'موبائل ایپ ڈیویلپمنٹ',
    'services.software': 'سافٹ ویئر ڈیویلپمنٹ',
    'services.outdoor': 'آؤٹ ڈور میڈیا ایڈورٹائزنگ',
    'services.blockchain': 'بلاک چین ڈیویلپمنٹ',
    'about.title': 'ہمارے بارے میں',
    'about.subtitle': 'ڈیجیٹل تبدیلی میں رہنمائی',
    'about.team': 'ہماری ٹیم',
    'about.partners': 'ہمارے شراکت دار',
    'contact.title': 'رابطہ کریں',
    'contact.subtitle': 'ہم آپ سے سننا پسند کریں گے',
    'contact.name': 'نام',
    'contact.email': 'ای میل',
    'contact.message': 'پیغام',
    'contact.send': 'پیغام بھیجیں',
    'footer.tagline': 'کل کے لیے جدید ڈیجیٹل حل',
    'footer.subscribe': 'ہمارے نیوز لیٹر کو سبسکرائب کریں',
    'footer.company': 'کمپنی',
    'footer.services': 'خدمات',
    'footer.resources': 'وسائل',
    'common.learnMore': 'مزید جانیں',
    'common.viewAll': 'سب دیکھیں',
    'common.readMore': 'مزید پڑھیں',
  },
  // Korean (South Korea)
  ko: {
    'nav.home': '홈',
    'nav.about': '회사 소개',
    'nav.services': '서비스',
    'nav.portfolio': '포트폴리오',
    'nav.blog': '블로그',
    'nav.pricing': '가격',
    'nav.contact': '연락처',
    'hero.title': '디지털 존재감을 혁신하세요',
    'hero.subtitle': '비즈니스 성장과 성공을 이끄는 혁신적인 디지털 솔루션을 제공합니다',
    'hero.cta': '시작하기',
    'hero.learn': '자세히 알아보기',
    'services.title': '서비스',
    'services.subtitle': '귀하의 요구에 맞춘 종합 디지털 솔루션',
    'services.ecommerce': '이커머스 개발',
    'services.web': '웹사이트 개발',
    'services.ppc': '구글 광고 (PPC)',
    'services.seo': '검색 엔진 최적화',
    'services.social': '소셜 미디어 마케팅',
    'services.mobile': '모바일 앱 개발',
    'services.software': '소프트웨어 개발',
    'services.outdoor': '옥외 광고',
    'services.blockchain': '블록체인 개발',
    'about.title': '회사 소개',
    'about.subtitle': '디지털 혁신을 선도합니다',
    'about.team': '팀 소개',
    'about.partners': '파트너사',
    'contact.title': '문의하기',
    'contact.subtitle': '연락 주시면 감사하겠습니다',
    'contact.name': '이름',
    'contact.email': '이메일',
    'contact.message': '메시지',
    'contact.send': '메시지 보내기',
    'footer.tagline': '내일을 위한 혁신적인 디지털 솔루션',
    'footer.subscribe': '뉴스레터 구독',
    'footer.company': '회사',
    'footer.services': '서비스',
    'footer.resources': '자료',
    'common.learnMore': '자세히 보기',
    'common.viewAll': '전체 보기',
    'common.readMore': '더 읽기',
  },
  // Chinese (Simplified)
  zh: {
    'nav.home': '首页',
    'nav.about': '关于我们',
    'nav.services': '服务',
    'nav.portfolio': '作品集',
    'nav.blog': '博客',
    'nav.pricing': '价格',
    'nav.contact': '联系我们',
    'hero.title': '转变您的数字化形象',
    'hero.subtitle': '我们打造创新的数字解决方案，推动您业务的增长与成功',
    'hero.cta': '立即开始',
    'hero.learn': '了解更多',
    'services.title': '我们的服务',
    'services.subtitle': '根据您的需求定制全面的数字解决方案',
    'services.ecommerce': '电子商务开发',
    'services.web': '网站开发',
    'services.ppc': '谷歌广告 (PPC)',
    'services.seo': '搜索引擎优化',
    'services.social': '社交媒体营销',
    'services.mobile': '移动应用开发',
    'services.software': '软件开发',
    'services.outdoor': '户外媒体广告',
    'services.blockchain': '区块链开发',
    'about.title': '关于我们',
    'about.subtitle': '引领数字化转型',
    'about.team': '我们的团队',
    'about.partners': '合作伙伴',
    'contact.title': '联系我们',
    'contact.subtitle': '期待您的来信',
    'contact.name': '姓名',
    'contact.email': '电子邮件',
    'contact.message': '留言',
    'contact.send': '发送消息',
    'footer.tagline': '为明天创新数字解决方案',
    'footer.subscribe': '订阅我们的新闻通讯',
    'footer.company': '公司',
    'footer.services': '服务',
    'footer.resources': '资源',
    'common.learnMore': '了解更多',
    'common.viewAll': '查看全部',
    'common.readMore': '阅读更多',
  },
  // Arabic (Saudi Arabia)
  ar: {
    'nav.home': 'الرئيسية',
    'nav.about': 'من نحن',
    'nav.services': 'الخدمات',
    'nav.portfolio': 'المحفظة',
    'nav.blog': 'المدونة',
    'nav.pricing': 'الأسعار',
    'nav.contact': 'اتصل بنا',
    'hero.title': 'حوّل حضورك الرقمي',
    'hero.subtitle': 'نحن نصنع حلولاً رقمية مبتكرة تدفع النمو والنجاح لعملك',
    'hero.cta': 'ابدأ الآن',
    'hero.learn': 'اعرف المزيد',
    'services.title': 'خدماتنا',
    'services.subtitle': 'حلول رقمية شاملة مصممة لاحتياجاتك',
    'services.ecommerce': 'تطوير التجارة الإلكترونية',
    'services.web': 'تطوير المواقع',
    'services.ppc': 'إعلانات جوجل (PPC)',
    'services.seo': 'تحسين محركات البحث',
    'services.social': 'التسويق عبر وسائل التواصل',
    'services.mobile': 'تطوير تطبيقات الجوال',
    'services.software': 'تطوير البرمجيات',
    'services.outdoor': 'الإعلانات الخارجية',
    'services.blockchain': 'تطوير البلوكتشين',
    'about.title': 'من نحن',
    'about.subtitle': 'نقود التحول الرقمي',
    'about.team': 'فريقنا',
    'about.partners': 'شركاؤنا',
    'contact.title': 'تواصل معنا',
    'contact.subtitle': 'نحب أن نسمع منك',
    'contact.name': 'الاسم',
    'contact.email': 'البريد الإلكتروني',
    'contact.message': 'الرسالة',
    'contact.send': 'إرسال الرسالة',
    'footer.tagline': 'ابتكار حلول رقمية للغد',
    'footer.subscribe': 'اشترك في نشرتنا الإخبارية',
    'footer.company': 'الشركة',
    'footer.services': 'الخدمات',
    'footer.resources': 'الموارد',
    'common.learnMore': 'اعرف المزيد',
    'common.viewAll': 'عرض الكل',
    'common.readMore': 'اقرأ المزيد',
  },
  // German (Germany)
  de: {
    'nav.home': 'Startseite',
    'nav.about': 'Über uns',
    'nav.services': 'Dienstleistungen',
    'nav.portfolio': 'Portfolio',
    'nav.blog': 'Blog',
    'nav.pricing': 'Preise',
    'nav.contact': 'Kontakt',
    'hero.title': 'Transformieren Sie Ihre digitale Präsenz',
    'hero.subtitle': 'Wir entwickeln innovative digitale Lösungen, die Wachstum und Erfolg für Ihr Unternehmen fördern',
    'hero.cta': 'Jetzt starten',
    'hero.learn': 'Mehr erfahren',
    'services.title': 'Unsere Dienstleistungen',
    'services.subtitle': 'Umfassende digitale Lösungen für Ihre Bedürfnisse',
    'services.ecommerce': 'E-Commerce Entwicklung',
    'services.web': 'Webentwicklung',
    'services.ppc': 'Google Ads (PPC)',
    'services.seo': 'Suchmaschinenoptimierung',
    'services.social': 'Social Media Marketing',
    'services.mobile': 'Mobile App Entwicklung',
    'services.software': 'Softwareentwicklung',
    'services.outdoor': 'Außenwerbung',
    'services.blockchain': 'Blockchain Entwicklung',
    'about.title': 'Über uns',
    'about.subtitle': 'Führend in der digitalen Transformation',
    'about.team': 'Unser Team',
    'about.partners': 'Unsere Partner',
    'contact.title': 'Kontaktieren Sie uns',
    'contact.subtitle': 'Wir freuen uns von Ihnen zu hören',
    'contact.name': 'Name',
    'contact.email': 'E-Mail',
    'contact.message': 'Nachricht',
    'contact.send': 'Nachricht senden',
    'footer.tagline': 'Innovative digitale Lösungen für morgen',
    'footer.subscribe': 'Newsletter abonnieren',
    'footer.company': 'Unternehmen',
    'footer.services': 'Dienstleistungen',
    'footer.resources': 'Ressourcen',
    'common.learnMore': 'Mehr erfahren',
    'common.viewAll': 'Alle anzeigen',
    'common.readMore': 'Weiterlesen',
  },
  // Spanish (Spain)
  es: {
    'nav.home': 'Inicio',
    'nav.about': 'Nosotros',
    'nav.services': 'Servicios',
    'nav.portfolio': 'Portafolio',
    'nav.blog': 'Blog',
    'nav.pricing': 'Precios',
    'nav.contact': 'Contacto',
    'hero.title': 'Transforma tu presencia digital',
    'hero.subtitle': 'Creamos soluciones digitales innovadoras que impulsan el crecimiento y éxito de tu negocio',
    'hero.cta': 'Comenzar',
    'hero.learn': 'Saber más',
    'services.title': 'Nuestros Servicios',
    'services.subtitle': 'Soluciones digitales integrales adaptadas a tus necesidades',
    'services.ecommerce': 'Desarrollo E-commerce',
    'services.web': 'Desarrollo Web',
    'services.ppc': 'Google Ads (PPC)',
    'services.seo': 'Optimización SEO',
    'services.social': 'Marketing en Redes Sociales',
    'services.mobile': 'Desarrollo de Apps Móviles',
    'services.software': 'Desarrollo de Software',
    'services.outdoor': 'Publicidad Exterior',
    'services.blockchain': 'Desarrollo Blockchain',
    'about.title': 'Sobre Nosotros',
    'about.subtitle': 'Liderando la transformación digital',
    'about.team': 'Nuestro Equipo',
    'about.partners': 'Nuestros Socios',
    'contact.title': 'Contáctanos',
    'contact.subtitle': 'Nos encantaría saber de ti',
    'contact.name': 'Nombre',
    'contact.email': 'Correo electrónico',
    'contact.message': 'Mensaje',
    'contact.send': 'Enviar mensaje',
    'footer.tagline': 'Innovando soluciones digitales para el mañana',
    'footer.subscribe': 'Suscríbete a nuestro boletín',
    'footer.company': 'Empresa',
    'footer.services': 'Servicios',
    'footer.resources': 'Recursos',
    'common.learnMore': 'Saber más',
    'common.viewAll': 'Ver todo',
    'common.readMore': 'Leer más',
  },
  // French (France)
  fr: {
    'nav.home': 'Accueil',
    'nav.about': 'À propos',
    'nav.services': 'Services',
    'nav.portfolio': 'Portfolio',
    'nav.blog': 'Blog',
    'nav.pricing': 'Tarifs',
    'nav.contact': 'Contact',
    'hero.title': 'Transformez votre présence numérique',
    'hero.subtitle': 'Nous créons des solutions numériques innovantes qui stimulent la croissance et le succès de votre entreprise',
    'hero.cta': 'Commencer',
    'hero.learn': 'En savoir plus',
    'services.title': 'Nos Services',
    'services.subtitle': 'Solutions numériques complètes adaptées à vos besoins',
    'services.ecommerce': 'Développement E-commerce',
    'services.web': 'Développement Web',
    'services.ppc': 'Google Ads (PPC)',
    'services.seo': 'Référencement SEO',
    'services.social': 'Marketing Réseaux Sociaux',
    'services.mobile': 'Développement Applications Mobiles',
    'services.software': 'Développement Logiciel',
    'services.outdoor': 'Publicité Extérieure',
    'services.blockchain': 'Développement Blockchain',
    'about.title': 'À propos de nous',
    'about.subtitle': 'Leader de la transformation numérique',
    'about.team': 'Notre Équipe',
    'about.partners': 'Nos Partenaires',
    'contact.title': 'Contactez-nous',
    'contact.subtitle': "Nous serions ravis d'avoir de vos nouvelles",
    'contact.name': 'Nom',
    'contact.email': 'E-mail',
    'contact.message': 'Message',
    'contact.send': 'Envoyer le message',
    'footer.tagline': 'Innover des solutions numériques pour demain',
    'footer.subscribe': 'Abonnez-vous à notre newsletter',
    'footer.company': 'Entreprise',
    'footer.services': 'Services',
    'footer.resources': 'Ressources',
    'common.learnMore': 'En savoir plus',
    'common.viewAll': 'Tout voir',
    'common.readMore': 'Lire la suite',
  },
  // Portuguese (Brazil)
  pt: {
    'nav.home': 'Início',
    'nav.about': 'Sobre Nós',
    'nav.services': 'Serviços',
    'nav.portfolio': 'Portfólio',
    'nav.blog': 'Blog',
    'nav.pricing': 'Preços',
    'nav.contact': 'Contato',
    'hero.title': 'Transforme sua presença digital',
    'hero.subtitle': 'Criamos soluções digitais inovadoras que impulsionam o crescimento e sucesso do seu negócio',
    'hero.cta': 'Começar',
    'hero.learn': 'Saiba mais',
    'services.title': 'Nossos Serviços',
    'services.subtitle': 'Soluções digitais completas adaptadas às suas necessidades',
    'services.ecommerce': 'Desenvolvimento E-commerce',
    'services.web': 'Desenvolvimento Web',
    'services.ppc': 'Google Ads (PPC)',
    'services.seo': 'Otimização SEO',
    'services.social': 'Marketing em Redes Sociais',
    'services.mobile': 'Desenvolvimento de Apps Móveis',
    'services.software': 'Desenvolvimento de Software',
    'services.outdoor': 'Mídia Exterior',
    'services.blockchain': 'Desenvolvimento Blockchain',
    'about.title': 'Sobre Nós',
    'about.subtitle': 'Liderando a transformação digital',
    'about.team': 'Nossa Equipe',
    'about.partners': 'Nossos Parceiros',
    'contact.title': 'Entre em Contato',
    'contact.subtitle': 'Adoraríamos ouvir você',
    'contact.name': 'Nome',
    'contact.email': 'E-mail',
    'contact.message': 'Mensagem',
    'contact.send': 'Enviar mensagem',
    'footer.tagline': 'Inovando soluções digitais para o amanhã',
    'footer.subscribe': 'Assine nossa newsletter',
    'footer.company': 'Empresa',
    'footer.services': 'Serviços',
    'footer.resources': 'Recursos',
    'common.learnMore': 'Saiba mais',
    'common.viewAll': 'Ver tudo',
    'common.readMore': 'Leia mais',
  },
  // Turkish (Turkey)
  tr: {
    'nav.home': 'Ana Sayfa',
    'nav.about': 'Hakkımızda',
    'nav.services': 'Hizmetler',
    'nav.portfolio': 'Portföy',
    'nav.blog': 'Blog',
    'nav.pricing': 'Fiyatlar',
    'nav.contact': 'İletişim',
    'hero.title': 'Dijital Varlığınızı Dönüştürün',
    'hero.subtitle': 'İşletmenizin büyümesini ve başarısını sağlayan yenilikçi dijital çözümler üretiyoruz',
    'hero.cta': 'Başlayın',
    'hero.learn': 'Daha Fazla Bilgi',
    'services.title': 'Hizmetlerimiz',
    'services.subtitle': 'İhtiyaçlarınıza göre tasarlanmış kapsamlı dijital çözümler',
    'services.ecommerce': 'E-ticaret Geliştirme',
    'services.web': 'Web Sitesi Geliştirme',
    'services.ppc': 'Google Reklamları (PPC)',
    'services.seo': 'Arama Motoru Optimizasyonu',
    'services.social': 'Sosyal Medya Pazarlama',
    'services.mobile': 'Mobil Uygulama Geliştirme',
    'services.software': 'Yazılım Geliştirme',
    'services.outdoor': 'Açık Hava Reklamcılığı',
    'services.blockchain': 'Blockchain Geliştirme',
    'about.title': 'Hakkımızda',
    'about.subtitle': 'Dijital dönüşümde öncü',
    'about.team': 'Ekibimiz',
    'about.partners': 'Ortaklarımız',
    'contact.title': 'Bize Ulaşın',
    'contact.subtitle': 'Sizden haber almak isteriz',
    'contact.name': 'Ad Soyad',
    'contact.email': 'E-posta',
    'contact.message': 'Mesaj',
    'contact.send': 'Mesaj Gönder',
    'footer.tagline': 'Yarın için yenilikçi dijital çözümler',
    'footer.subscribe': 'Bültenimize abone olun',
    'footer.company': 'Şirket',
    'footer.services': 'Hizmetler',
    'footer.resources': 'Kaynaklar',
    'common.learnMore': 'Daha Fazla',
    'common.viewAll': 'Tümünü Gör',
    'common.readMore': 'Devamını Oku',
  },
  // Dutch (Netherlands)
  nl: {
    'nav.home': 'Home',
    'nav.about': 'Over Ons',
    'nav.services': 'Diensten',
    'nav.portfolio': 'Portfolio',
    'nav.blog': 'Blog',
    'nav.pricing': 'Prijzen',
    'nav.contact': 'Contact',
    'hero.title': 'Transformeer uw digitale aanwezigheid',
    'hero.subtitle': 'Wij creëren innovatieve digitale oplossingen die groei en succes voor uw bedrijf stimuleren',
    'hero.cta': 'Aan de slag',
    'hero.learn': 'Meer informatie',
    'services.title': 'Onze Diensten',
    'services.subtitle': 'Uitgebreide digitale oplossingen op maat van uw behoeften',
    'services.ecommerce': 'E-commerce Ontwikkeling',
    'services.web': 'Website Ontwikkeling',
    'services.ppc': 'Google Ads (PPC)',
    'services.seo': 'Zoekmachineoptimalisatie',
    'services.social': 'Social Media Marketing',
    'services.mobile': 'Mobiele App Ontwikkeling',
    'services.software': 'Software Ontwikkeling',
    'services.outdoor': 'Buitenreclame',
    'services.blockchain': 'Blockchain Ontwikkeling',
    'about.title': 'Over Ons',
    'about.subtitle': 'Leider in digitale transformatie',
    'about.team': 'Ons Team',
    'about.partners': 'Onze Partners',
    'contact.title': 'Neem Contact Op',
    'contact.subtitle': 'We horen graag van u',
    'contact.name': 'Naam',
    'contact.email': 'E-mail',
    'contact.message': 'Bericht',
    'contact.send': 'Bericht verzenden',
    'footer.tagline': 'Innovatieve digitale oplossingen voor morgen',
    'footer.subscribe': 'Abonneer op onze nieuwsbrief',
    'footer.company': 'Bedrijf',
    'footer.services': 'Diensten',
    'footer.resources': 'Bronnen',
    'common.learnMore': 'Meer informatie',
    'common.viewAll': 'Alles bekijken',
    'common.readMore': 'Lees meer',
  },
  // Polish (Poland)
  pl: {
    'nav.home': 'Strona główna',
    'nav.about': 'O nas',
    'nav.services': 'Usługi',
    'nav.portfolio': 'Portfolio',
    'nav.blog': 'Blog',
    'nav.pricing': 'Cennik',
    'nav.contact': 'Kontakt',
    'hero.title': 'Przekształć swoją obecność cyfrową',
    'hero.subtitle': 'Tworzymy innowacyjne rozwiązania cyfrowe, które napędzają rozwój i sukces Twojej firmy',
    'hero.cta': 'Rozpocznij',
    'hero.learn': 'Dowiedz się więcej',
    'services.title': 'Nasze Usługi',
    'services.subtitle': 'Kompleksowe rozwiązania cyfrowe dostosowane do Twoich potrzeb',
    'services.ecommerce': 'Tworzenie E-commerce',
    'services.web': 'Tworzenie Stron WWW',
    'services.ppc': 'Google Ads (PPC)',
    'services.seo': 'Optymalizacja SEO',
    'services.social': 'Marketing w Mediach Społecznościowych',
    'services.mobile': 'Tworzenie Aplikacji Mobilnych',
    'services.software': 'Tworzenie Oprogramowania',
    'services.outdoor': 'Reklama Zewnętrzna',
    'services.blockchain': 'Rozwój Blockchain',
    'about.title': 'O Nas',
    'about.subtitle': 'Lider transformacji cyfrowej',
    'about.team': 'Nasz Zespół',
    'about.partners': 'Nasi Partnerzy',
    'contact.title': 'Skontaktuj się',
    'contact.subtitle': 'Chętnie usłyszymy od Ciebie',
    'contact.name': 'Imię i nazwisko',
    'contact.email': 'E-mail',
    'contact.message': 'Wiadomość',
    'contact.send': 'Wyślij wiadomość',
    'footer.tagline': 'Innowacyjne rozwiązania cyfrowe na jutro',
    'footer.subscribe': 'Zapisz się do newslettera',
    'footer.company': 'Firma',
    'footer.services': 'Usługi',
    'footer.resources': 'Zasoby',
    'common.learnMore': 'Dowiedz się więcej',
    'common.viewAll': 'Zobacz wszystko',
    'common.readMore': 'Czytaj dalej',
  },
  // Japanese (Japan)
  ja: {
    'nav.home': 'ホーム',
    'nav.about': '会社概要',
    'nav.services': 'サービス',
    'nav.portfolio': 'ポートフォリオ',
    'nav.blog': 'ブログ',
    'nav.pricing': '料金',
    'nav.contact': 'お問い合わせ',
    'hero.title': 'デジタルプレゼンスを変革する',
    'hero.subtitle': 'ビジネスの成長と成功を促進する革新的なデジタルソリューションを提供します',
    'hero.cta': '始める',
    'hero.learn': '詳細を見る',
    'services.title': 'サービス一覧',
    'services.subtitle': 'お客様のニーズに合わせた包括的なデジタルソリューション',
    'services.ecommerce': 'ECサイト開発',
    'services.web': 'ウェブサイト開発',
    'services.ppc': 'Google広告 (PPC)',
    'services.seo': '検索エンジン最適化',
    'services.social': 'ソーシャルメディアマーケティング',
    'services.mobile': 'モバイルアプリ開発',
    'services.software': 'ソフトウェア開発',
    'services.outdoor': '屋外広告',
    'services.blockchain': 'ブロックチェーン開発',
    'about.title': '会社概要',
    'about.subtitle': 'デジタル変革をリード',
    'about.team': '私たちのチーム',
    'about.partners': 'パートナー',
    'contact.title': 'お問い合わせ',
    'contact.subtitle': 'ご連絡をお待ちしております',
    'contact.name': 'お名前',
    'contact.email': 'メールアドレス',
    'contact.message': 'メッセージ',
    'contact.send': '送信する',
    'footer.tagline': '明日のための革新的なデジタルソリューション',
    'footer.subscribe': 'ニュースレターを購読',
    'footer.company': '会社',
    'footer.services': 'サービス',
    'footer.resources': 'リソース',
    'common.learnMore': '詳細を見る',
    'common.viewAll': 'すべて見る',
    'common.readMore': '続きを読む',
  },
  // Bengali (Bangladesh)
  bn: {
    'nav.home': 'হোম',
    'nav.about': 'আমাদের সম্পর্কে',
    'nav.services': 'সেবা',
    'nav.portfolio': 'পোর্টফোলিও',
    'nav.blog': 'ব্লগ',
    'nav.pricing': 'মূল্য',
    'nav.contact': 'যোগাযোগ',
    'hero.title': 'আপনার ডিজিটাল উপস্থিতি রূপান্তর করুন',
    'hero.subtitle': 'আমরা উদ্ভাবনী ডিজিটাল সমাধান তৈরি করি যা আপনার ব্যবসার বৃদ্ধি এবং সাফল্যকে চালিত করে',
    'hero.cta': 'শুরু করুন',
    'hero.learn': 'আরও জানুন',
    'services.title': 'আমাদের সেবা',
    'services.subtitle': 'আপনার প্রয়োজন অনুসারে ব্যাপক ডিজিটাল সমাধান',
    'services.ecommerce': 'ই-কমার্স ডেভেলপমেন্ট',
    'services.web': 'ওয়েবসাইট ডেভেলপমেন্ট',
    'services.ppc': 'গুগল বিজ্ঞাপন (PPC)',
    'services.seo': 'সার্চ ইঞ্জিন অপ্টিমাইজেশন',
    'services.social': 'সোশ্যাল মিডিয়া মার্কেটিং',
    'services.mobile': 'মোবাইল অ্যাপ ডেভেলপমেন্ট',
    'services.software': 'সফটওয়্যার ডেভেলপমেন্ট',
    'services.outdoor': 'আউটডোর মিডিয়া বিজ্ঞাপন',
    'services.blockchain': 'ব্লকচেইন ডেভেলপমেন্ট',
    'about.title': 'আমাদের সম্পর্কে',
    'about.subtitle': 'ডিজিটাল রূপান্তরে নেতৃত্ব',
    'about.team': 'আমাদের দল',
    'about.partners': 'আমাদের অংশীদার',
    'contact.title': 'যোগাযোগ করুন',
    'contact.subtitle': 'আমরা আপনার কাছ থেকে শুনতে চাই',
    'contact.name': 'নাম',
    'contact.email': 'ইমেইল',
    'contact.message': 'বার্তা',
    'contact.send': 'বার্তা পাঠান',
    'footer.tagline': 'আগামীর জন্য উদ্ভাবনী ডিজিটাল সমাধান',
    'footer.subscribe': 'আমাদের নিউজলেটার সাবস্ক্রাইব করুন',
    'footer.company': 'কোম্পানি',
    'footer.services': 'সেবা',
    'footer.resources': 'রিসোর্স',
    'common.learnMore': 'আরও জানুন',
    'common.viewAll': 'সবগুলো দেখুন',
    'common.readMore': 'আরও পড়ুন',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
