import React, { createContext, useContext, useState, ReactNode } from 'react';

// Define available languages
export type Language = 'en' | 'ur' | 'ko' | 'zh' | 'ar' | 'de' | 'es' | 'fr' | 'pt' | 'tr' | 'nl' | 'pl' | 'ja' | 'bn';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  // English
  en: {
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.services': 'Services',
    'nav.portfolio': 'Portfolio',
    'nav.blog': 'Blog',
    'nav.pricing': 'Pricing',
    'nav.contact': 'Contact',
    'hero.title': 'Transform Your Digital Presence',
    'hero.subtitle': 'We craft innovative digital solutions that drive growth and success for your business',
    'hero.cta': 'Get Started',
    'hero.learn': 'Learn More',
    'services.title': 'Our Services',
    'services.subtitle': 'Comprehensive digital solutions tailored to your needs',
    'services.ecommerce': 'E-commerce Development',
    'services.web': 'Website Development',
    'services.ppc': 'Google Ads (PPC)',
    'services.seo': 'Search Engine Optimization',
    'services.social': 'Social Media Marketing',
    'services.mobile': 'Mobile App Development',
    'services.software': 'Software Development',
    'services.outdoor': 'Outdoor Media Advertising',
    'services.blockchain': 'Blockchain Development',
    'about.title': 'About Us',
    'about.subtitle': 'Leading the digital transformation',
    'about.team': 'Our Team',
    'about.partners': 'Our Partners',
    'about.story': 'Our Story',
    'about.story.p1': 'Founded in 2010, NexGenTeck started with a simple mission: to help businesses harness the power of digital technology to achieve their goals.',
    'about.story.p2': "Over the years, we've grown from a small startup to a leading digital agency, serving clients across the globe. Our team of 50+ talented professionals brings together expertise in web development, mobile apps, digital marketing, and emerging technologies like blockchain.",
    'about.story.p3': "Today, we're proud to have completed over 500 successful projects and helped hundreds of businesses transform their digital presence.",
    'about.values': 'Our Values',
    'about.values.subtitle': 'The principles that guide everything we do',
    'about.values.innovation': 'Innovation',
    'about.values.innovation.desc': 'We constantly push boundaries and embrace new technologies to deliver cutting-edge solutions.',
    'about.values.collaboration': 'Collaboration',
    'about.values.collaboration.desc': 'We work closely with our clients as partners, ensuring their vision becomes reality.',
    'about.values.excellence': 'Excellence',
    'about.values.excellence.desc': 'We maintain the highest standards of quality in everything we do.',
    'about.values.passion': 'Passion',
    'about.values.passion.desc': 'We love what we do and it shows in the exceptional results we deliver.',
    'about.team.subtitle': 'Meet the talented people behind NexGenTeck',
    'about.partners.subtitle': 'Trusted by industry leaders worldwide',
    'about.partners.text': "We're proud to partner with the world's leading technology companies to deliver exceptional solutions to our clients.",
    'about.cta.title': 'Join Our Team',
    'about.cta.subtitle': "We're always looking for talented individuals to join our growing team",
    'about.cta.button': 'View Open Positions',
    'contact.title': 'Get In Touch',
    'contact.subtitle': "We'd love to hear from you",
    'contact.name': 'Name',
    'contact.email': 'Email',
    'contact.message': 'Message',
    'contact.send': 'Send Message',
    'footer.tagline': 'Innovating digital solutions for tomorrow',
    'footer.subscribe': 'Subscribe to our newsletter',
    'footer.company': 'Company',
    'footer.services': 'Services',
    'footer.resources': 'Resources',
    'common.learnMore': 'Learn More',
    'common.viewAll': 'View All',
    'common.readMore': 'Read More',
  },
  // Urdu (Pakistan)
  ur: {
    'nav.home': 'ہوم',
    'nav.about': 'ہمارے بارے میں',
    'nav.services': 'خدمات',
    'nav.portfolio': 'پورٹ فولیو',
    'nav.blog': 'بلاگ',
    'nav.pricing': 'قیمتیں',
    'nav.contact': 'رابطہ کریں',
    'hero.title': 'اپنی ڈیجیٹل موجودگی کو تبدیل کریں',
    'hero.subtitle': 'ہم جدید ڈیجیٹل حل تیار کرتے ہیں جو آپ کے کاروبار کی ترقی کو فروغ دیتے ہیں',
    'hero.cta': 'شروع کریں',
    'hero.learn': 'مزید جانیں',
    'services.title': 'ہماری خدمات',
    'services.subtitle': 'آپ کی ضروریات کے مطابق جامع ڈیجیٹل حل',
    'services.ecommerce': 'ای کامرس ڈیویلپمنٹ',
    'services.web': 'ویب سائٹ ڈیویلپمنٹ',
    'services.ppc': 'گوگل ایڈز (PPC)',
    'services.seo': 'سرچ انجن آپٹیمائزیشن',
    'services.social': 'سوشل میڈیا مارکیٹنگ',
    'services.mobile': 'موبائل ایپ ڈیویلپمنٹ',
    'services.software': 'سافٹ ویئر ڈیویلپمنٹ',
    'services.outdoor': 'آؤٹ ڈور میڈیا ایڈورٹائزنگ',
    'services.blockchain': 'بلاک چین ڈیویلپمنٹ',
    'about.title': 'ہمارے بارے میں',
    'about.subtitle': 'ڈیجیٹل تبدیلی میں رہنمائی',
    'about.team': 'ہماری ٹیم',
    'about.partners': 'ہمارے شراکت دار',
    'about.story': 'ہماری کہانی',
    'about.story.p1': '2010 میں قائم، NexGenTeck ایک سادہ مشن کے ساتھ شروع ہوا: کاروباروں کو ڈیجیٹل ٹیکنالوجی کی طاقت سے اپنے اہداف حاصل کرنے میں مدد کرنا۔',
    'about.story.p2': 'سالوں کے دوران، ہم ایک چھوٹے اسٹارٹ اپ سے عالمی سطح پر کلائنٹس کی خدمت کرنے والی ایک معروف ڈیجیٹل ایجنسی بن گئے ہیں۔',
    'about.story.p3': 'آج، ہمیں فخر ہے کہ ہم نے 500 سے زیادہ کامیاب پروجیکٹس مکمل کیے ہیں۔',
    'about.values': 'ہماری اقدار',
    'about.values.subtitle': 'وہ اصول جو ہماری ہر کام کی رہنمائی کرتے ہیں',
    'about.values.innovation': 'جدت',
    'about.values.innovation.desc': 'ہم مسلسل حدود کو آگے بڑھاتے ہیں اور جدید حل فراہم کرنے کے لیے نئی ٹیکنالوجیز اپناتے ہیں۔',
    'about.values.collaboration': 'تعاون',
    'about.values.collaboration.desc': 'ہم اپنے کلائنٹس کے ساتھ شراکت داروں کے طور پر مل کر کام کرتے ہیں۔',
    'about.values.excellence': 'عمدگی',
    'about.values.excellence.desc': 'ہم اپنے ہر کام میں اعلیٰ ترین معیار برقرار رکھتے ہیں۔',
    'about.values.passion': 'جذبہ',
    'about.values.passion.desc': 'ہمیں اپنے کام سے محبت ہے اور یہ ہمارے غیر معمولی نتائج میں ظاہر ہوتا ہے۔',
    'about.team.subtitle': 'NexGenTeck کے پیچھے باصلاحیت افراد سے ملیں',
    'about.partners.subtitle': 'دنیا بھر کے صنعتی رہنماؤں کا اعتماد',
    'about.partners.text': 'ہمیں فخر ہے کہ ہم دنیا کی معروف ٹیکنالوجی کمپنیوں کے ساتھ شراکت دار ہیں۔',
    'about.cta.title': 'ہماری ٹیم میں شامل ہوں',
    'about.cta.subtitle': 'ہم ہمیشہ باصلاحیت افراد کی تلاش میں رہتے ہیں',
    'about.cta.button': 'خالی آسامیاں دیکھیں',
    'contact.title': 'رابطہ کریں',
    'contact.subtitle': 'ہم آپ سے سننا پسند کریں گے',
    'contact.name': 'نام',
    'contact.email': 'ای میل',
    'contact.message': 'پیغام',
    'contact.send': 'پیغام بھیجیں',
    'footer.tagline': 'کل کے لیے جدید ڈیجیٹل حل',
    'footer.subscribe': 'ہمارے نیوز لیٹر کو سبسکرائب کریں',
    'footer.company': 'کمپنی',
    'footer.services': 'خدمات',
    'footer.resources': 'وسائل',
    'common.learnMore': 'مزید جانیں',
    'common.viewAll': 'سب دیکھیں',
    'common.readMore': 'مزید پڑھیں',
  },
  // Korean (South Korea)
  ko: {
    'nav.home': '홈',
    'nav.about': '회사 소개',
    'nav.services': '서비스',
    'nav.portfolio': '포트폴리오',
    'nav.blog': '블로그',
    'nav.pricing': '가격',
    'nav.contact': '연락처',
    'hero.title': '디지털 존재감을 혁신하세요',
    'hero.subtitle': '비즈니스 성장과 성공을 이끄는 혁신적인 디지털 솔루션을 제공합니다',
    'hero.cta': '시작하기',
    'hero.learn': '자세히 알아보기',
    'services.title': '서비스',
    'services.subtitle': '귀하의 요구에 맞춘 종합 디지털 솔루션',
    'services.ecommerce': '이커머스 개발',
    'services.web': '웹사이트 개발',
    'services.ppc': '구글 광고 (PPC)',
    'services.seo': '검색 엔진 최적화',
    'services.social': '소셜 미디어 마케팅',
    'services.mobile': '모바일 앱 개발',
    'services.software': '소프트웨어 개발',
    'services.outdoor': '옥외 광고',
    'services.blockchain': '블록체인 개발',
    'about.title': '회사 소개',
    'about.subtitle': '디지털 혁신을 선도합니다',
    'about.team': '팀 소개',
    'about.partners': '파트너사',
    'about.story': '우리의 이야기',
    'about.story.p1': '2010년에 설립된 NexGenTeck은 기업이 디지털 기술의 힘을 활용하여 목표를 달성할 수 있도록 돕는 간단한 사명으로 시작했습니다.',
    'about.story.p2': '수년에 걸쳐 우리는 소규모 스타트업에서 전 세계 고객에게 서비스를 제공하는 선도적인 디지털 에이전시로 성장했습니다.',
    'about.story.p3': '오늘날 우리는 500개 이상의 성공적인 프로젝트를 완료하고 수백 개의 기업이 디지털 전환을 이루도록 도왔습니다.',
    'about.values': '핵심 가치',
    'about.values.subtitle': '우리의 모든 일을 안내하는 원칙',
    'about.values.innovation': '혁신',
    'about.values.innovation.desc': '우리는 끊임없이 한계를 넓히고 최첨단 솔루션을 제공하기 위해 새로운 기술을 수용합니다.',
    'about.values.collaboration': '협력',
    'about.values.collaboration.desc': '우리는 고객과 파트너로서 긴밀히 협력하여 비전을 현실로 만듭니다.',
    'about.values.excellence': '탁월함',
    'about.values.excellence.desc': '우리는 모든 일에서 최고의 품질 기준을 유지합니다.',
    'about.values.passion': '열정',
    'about.values.passion.desc': '우리는 하는 일을 사랑하며 이는 탁월한 결과로 나타납니다.',
    'about.team.subtitle': 'NexGenTeck의 재능 있는 팀원들을 만나보세요',
    'about.partners.subtitle': '전 세계 업계 리더들의 신뢰',
    'about.partners.text': '우리는 세계 최고의 기술 회사들과 파트너십을 맺고 있습니다.',
    'about.cta.title': '팀에 합류하세요',
    'about.cta.subtitle': '성장하는 팀에 합류할 재능 있는 인재를 항상 찾고 있습니다',
    'about.cta.button': '채용 공고 보기',
    'contact.title': '문의하기',
    'contact.subtitle': '연락 주시면 감사하겠습니다',
    'contact.name': '이름',
    'contact.email': '이메일',
    'contact.message': '메시지',
    'contact.send': '메시지 보내기',
    'footer.tagline': '내일을 위한 혁신적인 디지털 솔루션',
    'footer.subscribe': '뉴스레터 구독',
    'footer.company': '회사',
    'footer.services': '서비스',
    'footer.resources': '자료',
    'common.learnMore': '자세히 보기',
    'common.viewAll': '전체 보기',
    'common.readMore': '더 읽기',
  },
  // Chinese (Simplified)
  zh: {
    'nav.home': '首页',
    'nav.about': '关于我们',
    'nav.services': '服务',
    'nav.portfolio': '作品集',
    'nav.blog': '博客',
    'nav.pricing': '价格',
    'nav.contact': '联系我们',
    'hero.title': '转变您的数字化形象',
    'hero.subtitle': '我们打造创新的数字解决方案，推动您业务的增长与成功',
    'hero.cta': '立即开始',
    'hero.learn': '了解更多',
    'services.title': '我们的服务',
    'services.subtitle': '根据您的需求定制全面的数字解决方案',
    'services.ecommerce': '电子商务开发',
    'services.web': '网站开发',
    'services.ppc': '谷歌广告 (PPC)',
    'services.seo': '搜索引擎优化',
    'services.social': '社交媒体营销',
    'services.mobile': '移动应用开发',
    'services.software': '软件开发',
    'services.outdoor': '户外媒体广告',
    'services.blockchain': '区块链开发',
    'about.title': '关于我们',
    'about.subtitle': '引领数字化转型',
    'about.team': '我们的团队',
    'about.partners': '合作伙伴',
    'about.story': '我们的故事',
    'about.story.p1': 'NexGenTeck成立于2010年，以一个简单的使命开始：帮助企业利用数字技术的力量实现目标。',
    'about.story.p2': '多年来，我们从一家小型创业公司成长为服务全球客户的领先数字机构。',
    'about.story.p3': '如今，我们已完成500多个成功项目，帮助数百家企业实现数字化转型。',
    'about.values': '核心价值观',
    'about.values.subtitle': '指导我们一切工作的原则',
    'about.values.innovation': '创新',
    'about.values.innovation.desc': '我们不断突破界限，拥抱新技术，提供尖端解决方案。',
    'about.values.collaboration': '协作',
    'about.values.collaboration.desc': '我们与客户紧密合作，将愿景变为现实。',
    'about.values.excellence': '卓越',
    'about.values.excellence.desc': '我们在所做的一切中保持最高的质量标准。',
    'about.values.passion': '热情',
    'about.values.passion.desc': '我们热爱我们的工作，这体现在卓越的成果中。',
    'about.team.subtitle': '认识NexGenTeck背后的人才团队',
    'about.partners.subtitle': '全球行业领袖的信赖',
    'about.partners.text': '我们很荣幸与世界领先的科技公司建立合作伙伴关系。',
    'about.cta.title': '加入我们的团队',
    'about.cta.subtitle': '我们一直在寻找优秀人才加入我们不断壮大的团队',
    'about.cta.button': '查看职位',
    'contact.title': '联系我们',
    'contact.subtitle': '期待您的来信',
    'contact.name': '姓名',
    'contact.email': '电子邮件',
    'contact.message': '留言',
    'contact.send': '发送消息',
    'footer.tagline': '为明天创新数字解决方案',
    'footer.subscribe': '订阅我们的新闻通讯',
    'footer.company': '公司',
    'footer.services': '服务',
    'footer.resources': '资源',
    'common.learnMore': '了解更多',
    'common.viewAll': '查看全部',
    'common.readMore': '阅读更多',
  },
  // Arabic (Saudi Arabia)
  ar: {
    'nav.home': 'الرئيسية',
    'nav.about': 'من نحن',
    'nav.services': 'الخدمات',
    'nav.portfolio': 'المحفظة',
    'nav.blog': 'المدونة',
    'nav.pricing': 'الأسعار',
    'nav.contact': 'اتصل بنا',
    'hero.title': 'حوّل حضورك الرقمي',
    'hero.subtitle': 'نحن نصنع حلولاً رقمية مبتكرة تدفع النمو والنجاح لعملك',
    'hero.cta': 'ابدأ الآن',
    'hero.learn': 'اعرف المزيد',
    'services.title': 'خدماتنا',
    'services.subtitle': 'حلول رقمية شاملة مصممة لاحتياجاتك',
    'services.ecommerce': 'تطوير التجارة الإلكترونية',
    'services.web': 'تطوير المواقع',
    'services.ppc': 'إعلانات جوجل (PPC)',
    'services.seo': 'تحسين محركات البحث',
    'services.social': 'التسويق عبر وسائل التواصل',
    'services.mobile': 'تطوير تطبيقات الجوال',
    'services.software': 'تطوير البرمجيات',
    'services.outdoor': 'الإعلانات الخارجية',
    'services.blockchain': 'تطوير البلوكتشين',
    'about.title': 'من نحن',
    'about.subtitle': 'نقود التحول الرقمي',
    'about.team': 'فريقنا',
    'about.partners': 'شركاؤنا',
    'about.story': 'قصتنا',
    'about.story.p1': 'تأسست NexGenTeck في عام 2010 بمهمة بسيطة: مساعدة الشركات على الاستفادة من قوة التكنولوجيا الرقمية.',
    'about.story.p2': 'على مدى السنوات، نمونا من شركة ناشئة صغيرة إلى وكالة رقمية رائدة تخدم عملاء حول العالم.',
    'about.story.p3': 'اليوم، نفخر بإكمال أكثر من 500 مشروع ناجح.',
    'about.values': 'قيمنا',
    'about.values.subtitle': 'المبادئ التي توجه كل ما نقوم به',
    'about.values.innovation': 'الابتكار',
    'about.values.innovation.desc': 'نحن نتخطى الحدود باستمرار ونتبنى تقنيات جديدة.',
    'about.values.collaboration': 'التعاون',
    'about.values.collaboration.desc': 'نعمل بشكل وثيق مع عملائنا كشركاء.',
    'about.values.excellence': 'التميز',
    'about.values.excellence.desc': 'نحافظ على أعلى معايير الجودة في كل ما نقوم به.',
    'about.values.passion': 'الشغف',
    'about.values.passion.desc': 'نحب ما نفعله ويظهر ذلك في النتائج.',
    'about.team.subtitle': 'تعرف على الفريق الموهوب وراء NexGenTeck',
    'about.partners.subtitle': 'موثوق به من قبل قادة الصناعة',
    'about.partners.text': 'نحن فخورون بالشراكة مع الشركات التقنية الرائدة.',
    'about.cta.title': 'انضم إلى فريقنا',
    'about.cta.subtitle': 'نبحث دائمًا عن أفراد موهوبين',
    'about.cta.button': 'عرض الوظائف',
    'contact.title': 'تواصل معنا',
    'contact.subtitle': 'نحب أن نسمع منك',
    'contact.name': 'الاسم',
    'contact.email': 'البريد الإلكتروني',
    'contact.message': 'الرسالة',
    'contact.send': 'إرسال الرسالة',
    'footer.tagline': 'ابتكار حلول رقمية للغد',
    'footer.subscribe': 'اشترك في نشرتنا الإخبارية',
    'footer.company': 'الشركة',
    'footer.services': 'الخدمات',
    'footer.resources': 'الموارد',
    'common.learnMore': 'اعرف المزيد',
    'common.viewAll': 'عرض الكل',
    'common.readMore': 'اقرأ المزيد',
  },
  // German (Germany)
  de: {
    'nav.home': 'Startseite',
    'nav.about': 'Über uns',
    'nav.services': 'Dienstleistungen',
    'nav.portfolio': 'Portfolio',
    'nav.blog': 'Blog',
    'nav.pricing': 'Preise',
    'nav.contact': 'Kontakt',
    'hero.title': 'Transformieren Sie Ihre digitale Präsenz',
    'hero.subtitle': 'Wir entwickeln innovative digitale Lösungen, die Wachstum und Erfolg für Ihr Unternehmen fördern',
    'hero.cta': 'Jetzt starten',
    'hero.learn': 'Mehr erfahren',
    'services.title': 'Unsere Dienstleistungen',
    'services.subtitle': 'Umfassende digitale Lösungen für Ihre Bedürfnisse',
    'services.ecommerce': 'E-Commerce Entwicklung',
    'services.web': 'Webentwicklung',
    'services.ppc': 'Google Ads (PPC)',
    'services.seo': 'Suchmaschinenoptimierung',
    'services.social': 'Social Media Marketing',
    'services.mobile': 'Mobile App Entwicklung',
    'services.software': 'Softwareentwicklung',
    'services.outdoor': 'Außenwerbung',
    'services.blockchain': 'Blockchain Entwicklung',
    'about.title': 'Über uns',
    'about.subtitle': 'Führend in der digitalen Transformation',
    'about.team': 'Unser Team',
    'about.partners': 'Unsere Partner',
    'about.story': 'Unsere Geschichte',
    'about.story.p1': 'NexGenTeck wurde 2010 mit einer einfachen Mission gegründet: Unternehmen dabei zu helfen, die Kraft der digitalen Technologie zu nutzen.',
    'about.story.p2': 'Im Laufe der Jahre sind wir von einem kleinen Startup zu einer führenden Digitalagentur gewachsen, die Kunden weltweit betreut.',
    'about.story.p3': 'Heute sind wir stolz darauf, über 500 erfolgreiche Projekte abgeschlossen zu haben.',
    'about.values': 'Unsere Werte',
    'about.values.subtitle': 'Die Prinzipien, die unser Handeln leiten',
    'about.values.innovation': 'Innovation',
    'about.values.innovation.desc': 'Wir überschreiten ständig Grenzen und setzen auf neue Technologien.',
    'about.values.collaboration': 'Zusammenarbeit',
    'about.values.collaboration.desc': 'Wir arbeiten eng mit unseren Kunden als Partner zusammen.',
    'about.values.excellence': 'Exzellenz',
    'about.values.excellence.desc': 'Wir halten die höchsten Qualitätsstandards in allem, was wir tun.',
    'about.values.passion': 'Leidenschaft',
    'about.values.passion.desc': 'Wir lieben, was wir tun, und das zeigt sich in unseren Ergebnissen.',
    'about.team.subtitle': 'Lernen Sie das talentierte Team hinter NexGenTeck kennen',
    'about.partners.subtitle': 'Vertraut von Branchenführern weltweit',
    'about.partners.text': 'Wir sind stolz darauf, mit führenden Technologieunternehmen zusammenzuarbeiten.',
    'about.cta.title': 'Werden Sie Teil unseres Teams',
    'about.cta.subtitle': 'Wir suchen immer nach talentierten Menschen',
    'about.cta.button': 'Offene Stellen ansehen',
    'contact.title': 'Kontaktieren Sie uns',
    'contact.subtitle': 'Wir freuen uns von Ihnen zu hören',
    'contact.name': 'Name',
    'contact.email': 'E-Mail',
    'contact.message': 'Nachricht',
    'contact.send': 'Nachricht senden',
    'footer.tagline': 'Innovative digitale Lösungen für morgen',
    'footer.subscribe': 'Newsletter abonnieren',
    'footer.company': 'Unternehmen',
    'footer.services': 'Dienstleistungen',
    'footer.resources': 'Ressourcen',
    'common.learnMore': 'Mehr erfahren',
    'common.viewAll': 'Alle anzeigen',
    'common.readMore': 'Weiterlesen',
  },
  // Spanish (Spain)
  es: {
    'nav.home': 'Inicio',
    'nav.about': 'Nosotros',
    'nav.services': 'Servicios',
    'nav.portfolio': 'Portafolio',
    'nav.blog': 'Blog',
    'nav.pricing': 'Precios',
    'nav.contact': 'Contacto',
    'hero.title': 'Transforma tu presencia digital',
    'hero.subtitle': 'Creamos soluciones digitales innovadoras que impulsan el crecimiento y éxito de tu negocio',
    'hero.cta': 'Comenzar',
    'hero.learn': 'Saber más',
    'services.title': 'Nuestros Servicios',
    'services.subtitle': 'Soluciones digitales integrales adaptadas a tus necesidades',
    'services.ecommerce': 'Desarrollo E-commerce',
    'services.web': 'Desarrollo Web',
    'services.ppc': 'Google Ads (PPC)',
    'services.seo': 'Optimización SEO',
    'services.social': 'Marketing en Redes Sociales',
    'services.mobile': 'Desarrollo de Apps Móviles',
    'services.software': 'Desarrollo de Software',
    'services.outdoor': 'Publicidad Exterior',
    'services.blockchain': 'Desarrollo Blockchain',
    'about.title': 'Sobre Nosotros',
    'about.subtitle': 'Liderando la transformación digital',
    'about.team': 'Nuestro Equipo',
    'about.partners': 'Nuestros Socios',
    'about.story': 'Nuestra Historia',
    'about.story.p1': 'NexGenTeck fue fundada en 2010 con una misión simple: ayudar a las empresas a aprovechar el poder de la tecnología digital.',
    'about.story.p2': 'A lo largo de los años, hemos crecido de una pequeña startup a una agencia digital líder que atiende a clientes en todo el mundo.',
    'about.story.p3': 'Hoy, nos enorgullece haber completado más de 500 proyectos exitosos.',
    'about.values': 'Nuestros Valores',
    'about.values.subtitle': 'Los principios que guían todo lo que hacemos',
    'about.values.innovation': 'Innovación',
    'about.values.innovation.desc': 'Constantemente superamos límites y adoptamos nuevas tecnologías.',
    'about.values.collaboration': 'Colaboración',
    'about.values.collaboration.desc': 'Trabajamos estrechamente con nuestros clientes como socios.',
    'about.values.excellence': 'Excelencia',
    'about.values.excellence.desc': 'Mantenemos los más altos estándares de calidad en todo lo que hacemos.',
    'about.values.passion': 'Pasión',
    'about.values.passion.desc': 'Amamos lo que hacemos y se refleja en nuestros resultados.',
    'about.team.subtitle': 'Conoce al talentoso equipo detrás de NexGenTeck',
    'about.partners.subtitle': 'Confiado por líderes de la industria',
    'about.partners.text': 'Estamos orgullosos de asociarnos con las principales empresas tecnológicas.',
    'about.cta.title': 'Únete a Nuestro Equipo',
    'about.cta.subtitle': 'Siempre buscamos personas talentosas',
    'about.cta.button': 'Ver Posiciones Abiertas',
    'contact.title': 'Contáctanos',
    'contact.subtitle': 'Nos encantaría saber de ti',
    'contact.name': 'Nombre',
    'contact.email': 'Correo electrónico',
    'contact.message': 'Mensaje',
    'contact.send': 'Enviar mensaje',
    'footer.tagline': 'Innovando soluciones digitales para el mañana',
    'footer.subscribe': 'Suscríbete a nuestro boletín',
    'footer.company': 'Empresa',
    'footer.services': 'Servicios',
    'footer.resources': 'Recursos',
    'common.learnMore': 'Saber más',
    'common.viewAll': 'Ver todo',
    'common.readMore': 'Leer más',
  },
  // French (France)
  fr: {
    'nav.home': 'Accueil',
    'nav.about': 'À propos',
    'nav.services': 'Services',
    'nav.portfolio': 'Portfolio',
    'nav.blog': 'Blog',
    'nav.pricing': 'Tarifs',
    'nav.contact': 'Contact',
    'hero.title': 'Transformez votre présence numérique',
    'hero.subtitle': 'Nous créons des solutions numériques innovantes qui stimulent la croissance et le succès de votre entreprise',
    'hero.cta': 'Commencer',
    'hero.learn': 'En savoir plus',
    'services.title': 'Nos Services',
    'services.subtitle': 'Solutions numériques complètes adaptées à vos besoins',
    'services.ecommerce': 'Développement E-commerce',
    'services.web': 'Développement Web',
    'services.ppc': 'Google Ads (PPC)',
    'services.seo': 'Référencement SEO',
    'services.social': 'Marketing Réseaux Sociaux',
    'services.mobile': 'Développement Applications Mobiles',
    'services.software': 'Développement Logiciel',
    'services.outdoor': 'Publicité Extérieure',
    'services.blockchain': 'Développement Blockchain',
    'about.title': 'À propos de nous',
    'about.subtitle': 'Leader de la transformation numérique',
    'about.team': 'Notre Équipe',
    'about.partners': 'Nos Partenaires',
    'about.story': 'Notre Histoire',
    'about.story.p1': "NexGenTeck a été fondée en 2010 avec une mission simple : aider les entreprises à exploiter la puissance de la technologie numérique.",
    'about.story.p2': "Au fil des années, nous sommes passés d'une petite startup à une agence numérique leader au service de clients du monde entier.",
    'about.story.p3': "Aujourd'hui, nous sommes fiers d'avoir réalisé plus de 500 projets réussis.",
    'about.values': 'Nos Valeurs',
    'about.values.subtitle': 'Les principes qui guident tout ce que nous faisons',
    'about.values.innovation': 'Innovation',
    'about.values.innovation.desc': 'Nous repoussons constamment les limites et adoptons de nouvelles technologies.',
    'about.values.collaboration': 'Collaboration',
    'about.values.collaboration.desc': 'Nous travaillons étroitement avec nos clients en tant que partenaires.',
    'about.values.excellence': 'Excellence',
    'about.values.excellence.desc': 'Nous maintenons les plus hauts standards de qualité dans tout ce que nous faisons.',
    'about.values.passion': 'Passion',
    'about.values.passion.desc': 'Nous aimons ce que nous faisons et cela se voit dans nos résultats.',
    'about.team.subtitle': "Découvrez l'équipe talentueuse derrière NexGenTeck",
    'about.partners.subtitle': "Approuvé par les leaders de l'industrie",
    'about.partners.text': 'Nous sommes fiers de nous associer aux principales entreprises technologiques.',
    'about.cta.title': 'Rejoignez Notre Équipe',
    'about.cta.subtitle': 'Nous recherchons toujours des personnes talentueuses',
    'about.cta.button': 'Voir les Postes Ouverts',
    'contact.title': 'Contactez-nous',
    'contact.subtitle': "Nous serions ravis d'avoir de vos nouvelles",
    'contact.name': 'Nom',
    'contact.email': 'E-mail',
    'contact.message': 'Message',
    'contact.send': 'Envoyer le message',
    'footer.tagline': 'Innover des solutions numériques pour demain',
    'footer.subscribe': 'Abonnez-vous à notre newsletter',
    'footer.company': 'Entreprise',
    'footer.services': 'Services',
    'footer.resources': 'Ressources',
    'common.learnMore': 'En savoir plus',
    'common.viewAll': 'Tout voir',
    'common.readMore': 'Lire la suite',
  },
  // Portuguese (Brazil)
  pt: {
    'nav.home': 'Início',
    'nav.about': 'Sobre Nós',
    'nav.services': 'Serviços',
    'nav.portfolio': 'Portfólio',
    'nav.blog': 'Blog',
    'nav.pricing': 'Preços',
    'nav.contact': 'Contato',
    'hero.title': 'Transforme sua presença digital',
    'hero.subtitle': 'Criamos soluções digitais inovadoras que impulsionam o crescimento e sucesso do seu negócio',
    'hero.cta': 'Começar',
    'hero.learn': 'Saiba mais',
    'services.title': 'Nossos Serviços',
    'services.subtitle': 'Soluções digitais completas adaptadas às suas necessidades',
    'services.ecommerce': 'Desenvolvimento E-commerce',
    'services.web': 'Desenvolvimento Web',
    'services.ppc': 'Google Ads (PPC)',
    'services.seo': 'Otimização SEO',
    'services.social': 'Marketing em Redes Sociais',
    'services.mobile': 'Desenvolvimento de Apps Móveis',
    'services.software': 'Desenvolvimento de Software',
    'services.outdoor': 'Mídia Exterior',
    'services.blockchain': 'Desenvolvimento Blockchain',
    'about.title': 'Sobre Nós',
    'about.subtitle': 'Liderando a transformação digital',
    'about.team': 'Nossa Equipe',
    'about.partners': 'Nossos Parceiros',
    'about.story': 'Nossa História',
    'about.story.p1': 'A NexGenTeck foi fundada em 2010 com uma missão simples: ajudar empresas a aproveitar o poder da tecnologia digital.',
    'about.story.p2': 'Ao longo dos anos, crescemos de uma pequena startup para uma agência digital líder atendendo clientes em todo o mundo.',
    'about.story.p3': 'Hoje, temos orgulho de ter concluído mais de 500 projetos de sucesso.',
    'about.values': 'Nossos Valores',
    'about.values.subtitle': 'Os princípios que guiam tudo o que fazemos',
    'about.values.innovation': 'Inovação',
    'about.values.innovation.desc': 'Estamos constantemente ultrapassando limites e abraçando novas tecnologias.',
    'about.values.collaboration': 'Colaboração',
    'about.values.collaboration.desc': 'Trabalhamos de perto com nossos clientes como parceiros.',
    'about.values.excellence': 'Excelência',
    'about.values.excellence.desc': 'Mantemos os mais altos padrões de qualidade em tudo o que fazemos.',
    'about.values.passion': 'Paixão',
    'about.values.passion.desc': 'Amamos o que fazemos e isso se reflete em nossos resultados.',
    'about.team.subtitle': 'Conheça a equipe talentosa por trás da NexGenTeck',
    'about.partners.subtitle': 'Confiado por líderes do setor',
    'about.partners.text': 'Temos orgulho de fazer parceria com as principais empresas de tecnologia.',
    'about.cta.title': 'Junte-se à Nossa Equipe',
    'about.cta.subtitle': 'Estamos sempre procurando pessoas talentosas',
    'about.cta.button': 'Ver Vagas Abertas',
    'contact.title': 'Entre em Contato',
    'contact.subtitle': 'Adoraríamos ouvir você',
    'contact.name': 'Nome',
    'contact.email': 'E-mail',
    'contact.message': 'Mensagem',
    'contact.send': 'Enviar mensagem',
    'footer.tagline': 'Inovando soluções digitais para o amanhã',
    'footer.subscribe': 'Assine nossa newsletter',
    'footer.company': 'Empresa',
    'footer.services': 'Serviços',
    'footer.resources': 'Recursos',
    'common.learnMore': 'Saiba mais',
    'common.viewAll': 'Ver tudo',
    'common.readMore': 'Leia mais',
  },
  // Turkish (Turkey)
  tr: {
    'nav.home': 'Ana Sayfa',
    'nav.about': 'Hakkımızda',
    'nav.services': 'Hizmetler',
    'nav.portfolio': 'Portföy',
    'nav.blog': 'Blog',
    'nav.pricing': 'Fiyatlar',
    'nav.contact': 'İletişim',
    'hero.title': 'Dijital Varlığınızı Dönüştürün',
    'hero.subtitle': 'İşletmenizin büyümesini ve başarısını sağlayan yenilikçi dijital çözümler üretiyoruz',
    'hero.cta': 'Başlayın',
    'hero.learn': 'Daha Fazla Bilgi',
    'services.title': 'Hizmetlerimiz',
    'services.subtitle': 'İhtiyaçlarınıza göre tasarlanmış kapsamlı dijital çözümler',
    'services.ecommerce': 'E-ticaret Geliştirme',
    'services.web': 'Web Sitesi Geliştirme',
    'services.ppc': 'Google Reklamları (PPC)',
    'services.seo': 'Arama Motoru Optimizasyonu',
    'services.social': 'Sosyal Medya Pazarlama',
    'services.mobile': 'Mobil Uygulama Geliştirme',
    'services.software': 'Yazılım Geliştirme',
    'services.outdoor': 'Açık Hava Reklamcılığı',
    'services.blockchain': 'Blockchain Geliştirme',
    'about.title': 'Hakkımızda',
    'about.subtitle': 'Dijital dönüşümde öncü',
    'about.team': 'Ekibimiz',
    'about.partners': 'Ortaklarımız',
    'about.story': 'Hikayemiz',
    'about.story.p1': 'NexGenTeck 2010 yılında basit bir misyonla kuruldu: işletmelerin dijital teknolojinin gücünden yararlanmasına yardımcı olmak.',
    'about.story.p2': 'Yıllar içinde küçük bir girişimden dünya çapında müşterilere hizmet veren lider bir dijital ajansa büyüdük.',
    'about.story.p3': 'Bugün, 500\'den fazla başarılı projeyi tamamlamış olmaktan gurur duyuyoruz.',
    'about.values': 'Değerlerimiz',
    'about.values.subtitle': 'Yaptığımız her şeye rehberlik eden ilkeler',
    'about.values.innovation': 'İnovasyon',
    'about.values.innovation.desc': 'Sürekli sınırları zorluyoruz ve yeni teknolojileri benimsiyoruz.',
    'about.values.collaboration': 'İşbirliği',
    'about.values.collaboration.desc': 'Müşterilerimizle partner olarak yakın çalışıyoruz.',
    'about.values.excellence': 'Mükemmellik',
    'about.values.excellence.desc': 'Yaptığımız her şeyde en yüksek kalite standartlarını koruyoruz.',
    'about.values.passion': 'Tutku',
    'about.values.passion.desc': 'Yaptığımız işi seviyoruz ve bu sonuçlarımıza yansıyor.',
    'about.team.subtitle': 'NexGenTeck\'in arkasındaki yetenekli ekibi tanıyın',
    'about.partners.subtitle': 'Sektör liderleri tarafından güveniliyor',
    'about.partners.text': 'Önde gelen teknoloji şirketleriyle ortaklık kurmaktan gurur duyuyoruz.',
    'about.cta.title': 'Ekibimize Katılın',
    'about.cta.subtitle': 'Her zaman yetenekli bireyler arıyoruz',
    'about.cta.button': 'Açık Pozisyonları Görüntüle',
    'contact.title': 'Bize Ulaşın',
    'contact.subtitle': 'Sizden haber almak isteriz',
    'contact.name': 'Ad Soyad',
    'contact.email': 'E-posta',
    'contact.message': 'Mesaj',
    'contact.send': 'Mesaj Gönder',
    'footer.tagline': 'Yarın için yenilikçi dijital çözümler',
    'footer.subscribe': 'Bültenimize abone olun',
    'footer.company': 'Şirket',
    'footer.services': 'Hizmetler',
    'footer.resources': 'Kaynaklar',
    'common.learnMore': 'Daha Fazla',
    'common.viewAll': 'Tümünü Gör',
    'common.readMore': 'Devamını Oku',
  },
  // Dutch (Netherlands)
  nl: {
    'nav.home': 'Home',
    'nav.about': 'Over Ons',
    'nav.services': 'Diensten',
    'nav.portfolio': 'Portfolio',
    'nav.blog': 'Blog',
    'nav.pricing': 'Prijzen',
    'nav.contact': 'Contact',
    'hero.title': 'Transformeer uw digitale aanwezigheid',
    'hero.subtitle': 'Wij creëren innovatieve digitale oplossingen die groei en succes voor uw bedrijf stimuleren',
    'hero.cta': 'Aan de slag',
    'hero.learn': 'Meer informatie',
    'services.title': 'Onze Diensten',
    'services.subtitle': 'Uitgebreide digitale oplossingen op maat van uw behoeften',
    'services.ecommerce': 'E-commerce Ontwikkeling',
    'services.web': 'Website Ontwikkeling',
    'services.ppc': 'Google Ads (PPC)',
    'services.seo': 'Zoekmachineoptimalisatie',
    'services.social': 'Social Media Marketing',
    'services.mobile': 'Mobiele App Ontwikkeling',
    'services.software': 'Software Ontwikkeling',
    'services.outdoor': 'Buitenreclame',
    'services.blockchain': 'Blockchain Ontwikkeling',
    'about.title': 'Over Ons',
    'about.subtitle': 'Leider in digitale transformatie',
    'about.team': 'Ons Team',
    'about.partners': 'Onze Partners',
    'about.story': 'Ons Verhaal',
    'about.story.p1': 'NexGenTeck werd in 2010 opgericht met een eenvoudige missie: bedrijven helpen de kracht van digitale technologie te benutten.',
    'about.story.p2': 'Door de jaren heen zijn we gegroeid van een kleine startup naar een toonaangevend digitaal bureau dat klanten wereldwijd bedient.',
    'about.story.p3': 'Vandaag zijn we trots op het voltooien van meer dan 500 succesvolle projecten.',
    'about.values': 'Onze Waarden',
    'about.values.subtitle': 'De principes die alles wat we doen sturen',
    'about.values.innovation': 'Innovatie',
    'about.values.innovation.desc': 'We verleggen voortdurend grenzen en omarmen nieuwe technologieën.',
    'about.values.collaboration': 'Samenwerking',
    'about.values.collaboration.desc': 'We werken nauw samen met onze klanten als partners.',
    'about.values.excellence': 'Excellentie',
    'about.values.excellence.desc': 'We hanteren de hoogste kwaliteitsnormen in alles wat we doen.',
    'about.values.passion': 'Passie',
    'about.values.passion.desc': 'We houden van wat we doen en dat zie je terug in onze resultaten.',
    'about.team.subtitle': 'Maak kennis met het getalenteerde team achter NexGenTeck',
    'about.partners.subtitle': 'Vertrouwd door marktleiders',
    'about.partners.text': 'We zijn trots op onze partnerschappen met vooraanstaande technologiebedrijven.',
    'about.cta.title': 'Word Lid van Ons Team',
    'about.cta.subtitle': 'We zijn altijd op zoek naar getalenteerde mensen',
    'about.cta.button': 'Bekijk Vacatures',
    'contact.title': 'Neem Contact Op',
    'contact.subtitle': 'We horen graag van u',
    'contact.name': 'Naam',
    'contact.email': 'E-mail',
    'contact.message': 'Bericht',
    'contact.send': 'Bericht verzenden',
    'footer.tagline': 'Innovatieve digitale oplossingen voor morgen',
    'footer.subscribe': 'Abonneer op onze nieuwsbrief',
    'footer.company': 'Bedrijf',
    'footer.services': 'Diensten',
    'footer.resources': 'Bronnen',
    'common.learnMore': 'Meer informatie',
    'common.viewAll': 'Alles bekijken',
    'common.readMore': 'Lees meer',
  },
  // Polish (Poland)
  pl: {
    'nav.home': 'Strona główna',
    'nav.about': 'O nas',
    'nav.services': 'Usługi',
    'nav.portfolio': 'Portfolio',
    'nav.blog': 'Blog',
    'nav.pricing': 'Cennik',
    'nav.contact': 'Kontakt',
    'hero.title': 'Przekształć swoją obecność cyfrową',
    'hero.subtitle': 'Tworzymy innowacyjne rozwiązania cyfrowe, które napędzają rozwój i sukces Twojej firmy',
    'hero.cta': 'Rozpocznij',
    'hero.learn': 'Dowiedz się więcej',
    'services.title': 'Nasze Usługi',
    'services.subtitle': 'Kompleksowe rozwiązania cyfrowe dostosowane do Twoich potrzeb',
    'services.ecommerce': 'Tworzenie E-commerce',
    'services.web': 'Tworzenie Stron WWW',
    'services.ppc': 'Google Ads (PPC)',
    'services.seo': 'Optymalizacja SEO',
    'services.social': 'Marketing w Mediach Społecznościowych',
    'services.mobile': 'Tworzenie Aplikacji Mobilnych',
    'services.software': 'Tworzenie Oprogramowania',
    'services.outdoor': 'Reklama Zewnętrzna',
    'services.blockchain': 'Rozwój Blockchain',
    'about.title': 'O Nas',
    'about.subtitle': 'Lider transformacji cyfrowej',
    'about.team': 'Nasz Zespół',
    'about.partners': 'Nasi Partnerzy',
    'about.story': 'Nasza Historia',
    'about.story.p1': 'NexGenTeck została założona w 2010 roku z prostą misją: pomagać firmom wykorzystać moc technologii cyfrowej.',
    'about.story.p2': 'Przez lata rozwinęliśmy się z małego startupu w wiodącą agencję cyfrową obsługującą klientów na całym świecie.',
    'about.story.p3': 'Dziś jesteśmy dumni z realizacji ponad 500 udanych projektów.',
    'about.values': 'Nasze Wartości',
    'about.values.subtitle': 'Zasady, które kierują wszystkim, co robimy',
    'about.values.innovation': 'Innowacja',
    'about.values.innovation.desc': 'Nieustannie przesuwamy granice i wdrażamy nowe technologie.',
    'about.values.collaboration': 'Współpraca',
    'about.values.collaboration.desc': 'Ściśle współpracujemy z naszymi klientami jako partnerzy.',
    'about.values.excellence': 'Doskonałość',
    'about.values.excellence.desc': 'Utrzymujemy najwyższe standardy jakości we wszystkim, co robimy.',
    'about.values.passion': 'Pasja',
    'about.values.passion.desc': 'Kochamy to, co robimy, i widać to w naszych wynikach.',
    'about.team.subtitle': 'Poznaj utalentowany zespół stojący za NexGenTeck',
    'about.partners.subtitle': 'Zaufany przez liderów branży',
    'about.partners.text': 'Jesteśmy dumni z partnerstwa z wiodącymi firmami technologicznymi.',
    'about.cta.title': 'Dołącz do Naszego Zespołu',
    'about.cta.subtitle': 'Zawsze szukamy utalentowanych osób',
    'about.cta.button': 'Zobacz Oferty Pracy',
    'contact.title': 'Skontaktuj się',
    'contact.subtitle': 'Chętnie usłyszymy od Ciebie',
    'contact.name': 'Imię i nazwisko',
    'contact.email': 'E-mail',
    'contact.message': 'Wiadomość',
    'contact.send': 'Wyślij wiadomość',
    'footer.tagline': 'Innowacyjne rozwiązania cyfrowe na jutro',
    'footer.subscribe': 'Zapisz się do newslettera',
    'footer.company': 'Firma',
    'footer.services': 'Usługi',
    'footer.resources': 'Zasoby',
    'common.learnMore': 'Dowiedz się więcej',
    'common.viewAll': 'Zobacz wszystko',
    'common.readMore': 'Czytaj dalej',
  },
  // Japanese (Japan)
  ja: {
    'nav.home': 'ホーム',
    'nav.about': '会社概要',
    'nav.services': 'サービス',
    'nav.portfolio': 'ポートフォリオ',
    'nav.blog': 'ブログ',
    'nav.pricing': '料金',
    'nav.contact': 'お問い合わせ',
    'hero.title': 'デジタルプレゼンスを変革する',
    'hero.subtitle': 'ビジネスの成長と成功を促進する革新的なデジタルソリューションを提供します',
    'hero.cta': '始める',
    'hero.learn': '詳細を見る',
    'services.title': 'サービス一覧',
    'services.subtitle': 'お客様のニーズに合わせた包括的なデジタルソリューション',
    'services.ecommerce': 'ECサイト開発',
    'services.web': 'ウェブサイト開発',
    'services.ppc': 'Google広告 (PPC)',
    'services.seo': '検索エンジン最適化',
    'services.social': 'ソーシャルメディアマーケティング',
    'services.mobile': 'モバイルアプリ開発',
    'services.software': 'ソフトウェア開発',
    'services.outdoor': '屋外広告',
    'services.blockchain': 'ブロックチェーン開発',
    'about.title': '会社概要',
    'about.subtitle': 'デジタル変革をリード',
    'about.team': '私たちのチーム',
    'about.partners': 'パートナー',
    'about.story': '私たちの物語',
    'about.story.p1': 'NexGenTeckは2010年にシンプルな使命で設立されました：企業がデジタル技術の力を活用できるよう支援すること。',
    'about.story.p2': '長年にわたり、小さなスタートアップから世界中のクライアントにサービスを提供するリーディングデジタルエージェンシーへと成長しました。',
    'about.story.p3': '今日、500以上の成功プロジェクトを完了したことを誇りに思います。',
    'about.values': '私たちの価値観',
    'about.values.subtitle': '私たちの行動を導く原則',
    'about.values.innovation': 'イノベーション',
    'about.values.innovation.desc': '常に限界を押し広げ、新しい技術を取り入れています。',
    'about.values.collaboration': 'コラボレーション',
    'about.values.collaboration.desc': 'クライアントとパートナーとして緊密に協力しています。',
    'about.values.excellence': '卓越性',
    'about.values.excellence.desc': 'すべての業務において最高品質基準を維持しています。',
    'about.values.passion': '情熱',
    'about.values.passion.desc': '私たちは自分たちの仕事を愛しており、それは結果に表れています。',
    'about.team.subtitle': 'NexGenTeckの背後にある才能あるチームをご紹介',
    'about.partners.subtitle': '業界リーダーから信頼されています',
    'about.partners.text': '世界有数のテクノロジー企業とパートナーシップを結んでいることを誇りに思います。',
    'about.cta.title': 'チームに参加しませんか',
    'about.cta.subtitle': '才能ある人材を常に募集しています',
    'about.cta.button': '募集職種を見る',
    'contact.title': 'お問い合わせ',
    'contact.subtitle': 'ご連絡をお待ちしております',
    'contact.name': 'お名前',
    'contact.email': 'メールアドレス',
    'contact.message': 'メッセージ',
    'contact.send': '送信する',
    'footer.tagline': '明日のための革新的なデジタルソリューション',
    'footer.subscribe': 'ニュースレターを購読',
    'footer.company': '会社',
    'footer.services': 'サービス',
    'footer.resources': 'リソース',
    'common.learnMore': '詳細を見る',
    'common.viewAll': 'すべて見る',
    'common.readMore': '続きを読む',
  },
  // Bengali (Bangladesh)
  bn: {
    'nav.home': 'হোম',
    'nav.about': 'আমাদের সম্পর্কে',
    'nav.services': 'সেবা',
    'nav.portfolio': 'পোর্টফোলিও',
    'nav.blog': 'ব্লগ',
    'nav.pricing': 'মূল্য',
    'nav.contact': 'যোগাযোগ',
    'hero.title': 'আপনার ডিজিটাল উপস্থিতি রূপান্তর করুন',
    'hero.subtitle': 'আমরা উদ্ভাবনী ডিজিটাল সমাধান তৈরি করি যা আপনার ব্যবসার বৃদ্ধি এবং সাফল্যকে চালিত করে',
    'hero.cta': 'শুরু করুন',
    'hero.learn': 'আরও জানুন',
    'services.title': 'আমাদের সেবা',
    'services.subtitle': 'আপনার প্রয়োজন অনুসারে ব্যাপক ডিজিটাল সমাধান',
    'services.ecommerce': 'ই-কমার্স ডেভেলপমেন্ট',
    'services.web': 'ওয়েবসাইট ডেভেলপমেন্ট',
    'services.ppc': 'গুগল বিজ্ঞাপন (PPC)',
    'services.seo': 'সার্চ ইঞ্জিন অপ্টিমাইজেশন',
    'services.social': 'সোশ্যাল মিডিয়া মার্কেটিং',
    'services.mobile': 'মোবাইল অ্যাপ ডেভেলপমেন্ট',
    'services.software': 'সফটওয়্যার ডেভেলপমেন্ট',
    'services.outdoor': 'আউটডোর মিডিয়া বিজ্ঞাপন',
    'services.blockchain': 'ব্লকচেইন ডেভেলপমেন্ট',
    'about.title': 'আমাদের সম্পর্কে',
    'about.subtitle': 'ডিজিটাল রূপান্তরে নেতৃত্ব',
    'about.team': 'আমাদের দল',
    'about.partners': 'আমাদের অংশীদার',
    'about.story': 'আমাদের গল্প',
    'about.story.p1': 'NexGenTeck 2010 সালে একটি সাধারণ মিশন নিয়ে প্রতিষ্ঠিত হয়েছিল: ব্যবসাগুলিকে ডিজিটাল প্রযুক্তির শক্তি ব্যবহার করতে সাহায্য করা।',
    'about.story.p2': 'বছরের পর বছর ধরে, আমরা একটি ছোট স্টার্টআপ থেকে বিশ্বব্যাপী ক্লায়েন্টদের সেবা দেওয়া একটি শীর্ষস্থানীয় ডিজিটাল এজেন্সিতে পরিণত হয়েছি।',
    'about.story.p3': 'আজ, আমরা 500 টিরও বেশি সফল প্রকল্প সম্পন্ন করেছি।',
    'about.values': 'আমাদের মূল্যবোধ',
    'about.values.subtitle': 'যে নীতিগুলি আমাদের সমস্ত কাজকে পরিচালিত করে',
    'about.values.innovation': 'উদ্ভাবন',
    'about.values.innovation.desc': 'আমরা ক্রমাগত সীমানা প্রসারিত করি এবং নতুন প্রযুক্তি গ্রহণ করি।',
    'about.values.collaboration': 'সহযোগিতা',
    'about.values.collaboration.desc': 'আমরা আমাদের ক্লায়েন্টদের সাথে অংশীদার হিসেবে ঘনিষ্ঠভাবে কাজ করি।',
    'about.values.excellence': 'শ্রেষ্ঠত্ব',
    'about.values.excellence.desc': 'আমরা সবকিছুতে সর্বোচ্চ মানের মান বজায় রাখি।',
    'about.values.passion': 'আবেগ',
    'about.values.passion.desc': 'আমরা যা করি তা ভালোবাসি এবং এটি আমাদের ফলাফলে প্রতিফলিত হয়।',
    'about.team.subtitle': 'NexGenTeck এর পিছনে প্রতিভাবান দলের সাথে পরিচিত হন',
    'about.partners.subtitle': 'শিল্প নেতাদের দ্বারা বিশ্বস্ত',
    'about.partners.text': 'আমরা বিশ্বের শীর্ষস্থানীয় প্রযুক্তি কোম্পানিগুলির সাথে অংশীদারিত্ব করতে পেরে গর্বিত।',
    'about.cta.title': 'আমাদের দলে যোগ দিন',
    'about.cta.subtitle': 'আমরা সবসময় প্রতিভাবান ব্যক্তিদের খুঁজি',
    'about.cta.button': 'খালি পদগুলি দেখুন',
    'contact.title': 'যোগাযোগ করুন',
    'contact.subtitle': 'আমরা আপনার কাছ থেকে শুনতে চাই',
    'contact.name': 'নাম',
    'contact.email': 'ইমেইল',
    'contact.message': 'বার্তা',
    'contact.send': 'বার্তা পাঠান',
    'footer.tagline': 'আগামীর জন্য উদ্ভাবনী ডিজিটাল সমাধান',
    'footer.subscribe': 'আমাদের নিউজলেটার সাবস্ক্রাইব করুন',
    'footer.company': 'কোম্পানি',
    'footer.services': 'সেবা',
    'footer.resources': 'রিসোর্স',
    'common.learnMore': 'আরও জানুন',
    'common.viewAll': 'সবগুলো দেখুন',
    'common.readMore': 'আরও পড়ুন',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
